Script started on 2022-05-21 21:07:50-06:00
]0;maximilian.kaczmarek@csa3:~/assignment2maximilian.kaczmarek@csa3:~/assignment2$ exit./assign2a[Kb
Enter the number of positive integers you want:
0
0
There are no numbers
]0;maximilian.kaczmarek@csa3:~/assignment2maximilian.kaczmarek@csa3:~/assignment2$ 1
bash: 1: command not found
]0;maximilian.kaczmarek@csa3:~/assignment2maximilian.kaczmarek@csa3:~/assignment2$ 1./assign2b
Enter the number of positive integers you want:
1
1804289383
1804289383
There is only one value
]0;maximilian.kaczmarek@csa3:~/assignment2maximilian.kaczmarek@csa3:~/assignment2$ ./assign2b
Enter the number of positive integers you want:
2
1804289383
846930886
2651220269
The numbers are Descending
]0;maximilian.kaczmarek@csa3:~/assignment2maximilian.kaczmarek@csa3:~/assignment2$ ./assign2b
Enter the number of positive integers you want:
4
1804289383
846930886
1681692777
1714636915
6047549961
The numbers are not in order
]0;maximilian.kaczmarek@csa3:~/assignment2maximilian.kaczmarek@csa3:~/assignment2$ exit
exit

Script done on 2022-05-21 21:08:29-06:00
