Script started on 2022-05-15 22:24:08-06:00
No such schema “org.gnome.gedit.preferences.editor”
]0;maximilian.kaczmarek@csa1:~maximilian.kaczmarek@csa1:~$ ./assign1 5
7 6 1 3 1 
7 2 4 1 5 
2 3 2 3 3 
6 4 2 4 0 
3 0 7 5 6 

Enter a digit to search for (or press q to quit): 7

1: Digit found at coordinate 0, 0
2: Digit found at coordinate 1, 0
3: Digit found at coordinate 4, 2

Your digit occurs 3 times.
The digit 7 is 12 % of the matrix.

Enter a digit to search for (or press q to quit): 1

1: Digit found at coordinate 0, 2
2: Digit found at coordinate 0, 4
3: Digit found at coordinate 1, 3

Your digit occurs 3 times.
The digit 1 is 12 % of the matrix.

Enter a digit to search for (or press q to quit): q
Exiting!
]0;maximilian.kaczmarek@csa1:~maximilian.kaczmarek@csa1:~$ ./assign1 8
7 6 1 3 1 7 2 4 
1 5 2 3 2 3 3 6 
4 2 4 0 3 0 7 5 
6 2 6 3 3 7 1 2 
6 2 5 7 1 0 3 2 
5 5 5 7 0 1 6 4 
3 2 5 6 3 4 4 1 
6 2 4 1 1 5 4 7 

Enter a digit to search for (or press q to quit): 4

1: Digit found at coordinate 0, 7
2: Digit found at coordinate 2, 0
3: Digit found at coordinate 2, 2
4: Digit found at coordinate 5, 7
5: Digit found at coordinate 6, 5
6: Digit found at coordinate 6, 6
7: Digit found at coordinate 7, 2
8: Digit found at coordinate 7, 6

Your digit occurs 8 times.
The digit 4 is 12 % of the matrix.

Enter a digit to search for (or press q to quit): -3
No negative numbers allowed
Enter a digit to search for (or press q to quit): -2
No negative numbers allowed
Enter a digit to search for (or press q to quit): 0

1: Digit found at coordinate 2, 3
2: Digit found at coordinate 2, 5
3: Digit found at coordinate 4, 5
4: Digit found at coordinate 5, 4

Your digit occurs 4 times.
The digit 0 is 6 % of the matrix.

Enter a digit to search for (or press q to quit): q
Exiting!
]0;maximilian.kaczmarek@csa1:~maximilian.kaczmarek@csa1:~$ cat assign1.log
7 6 1 3 1 7 2 4 
1 5 2 3 2 3 3 6 
4 2 4 0 3 0 7 5 
6 2 6 3 3 7 1 2 
6 2 5 7 1 0 3 2 
5 5 5 7 0 1 6 4 
3 2 5 6 3 4 4 1 
6 2 4 1 1 5 4 7 
Enter a digit to search for (or press q to quit): 
41: Digit found at coordinate 0, 7
2: Digit found at coordinate 2, 0
3: Digit found at coordinate 2, 2
4: Digit found at coordinate 5, 7
5: Digit found at coordinate 6, 5
6: Digit found at coordinate 6, 6
7: Digit found at coordinate 7, 2
8: Digit found at coordinate 7, 6
Your digit occurs 8 times.
The digit 4 is 12 % of the matrix.

Enter a digit to search for (or press q to quit): 
-3No negative numbers allowed
Enter a digit to search for (or press q to quit): 
-2No negative numbers allowed
Enter a digit to search for (or press q to quit): 
01: Digit found at coordinate 2, 3
2: Digit found at coordinate 2, 5
3: Digit found at coordinate 4, 5
4: Digit found at coordinate 5, 4
Your digit occurs 4 times.
The digit 0 is 6 % of the matrix.

Enter a digit to search for (or press q to quit): 
qExiting!
]0;maximilian.kaczmarek@csa1:~maximilian.kaczmarek@csa1:~$ exit
exit

Script done on 2022-05-15 22:25:44-06:00
