Script started on 2022-06-06 20:11:38-06:00
]0;maximilian.kaczmarek@csa3:~/assignment4maximilian.kaczmarek@csa3:~/assignment4$ ./assign4
Enter the size of the table:
5
 5  6  2  7  1 
 2  6  7  7  2 
 0  3  8  3  5 
 1  2  2  7  4 
 5  0  7  2  7 
Enter a digit to search for (or press q to quit): 7
Digit 7 occurrences:
1. In (0,3)
2. In (1,2)
3. In (1,3)
4. In (3,3)
5. In (4,2)
6. In (4,4)
Enter a digit to search for (or press q to quit): 6
Digit 6 occurrences:
1. In (0,1)
2. In (1,1)
Enter a digit to search for (or press q to quit): 1
Digit 1 occurrences:
1. In (0,4)
2. In (3,0)
Enter a digit to search for (or press q to quit): q
]0;maximilian.kaczmarek@csa3:~/assignment4maximilian.kaczmarek@csa3:~/assignment4$ ./assign4
Enter the size of the table:
12
 4  1  1  4  0  1  0  5  0  1  7  5 
 3  1  7  3  2  0  0  8  4  4  5  6 
 5  7  6  3  5  7  2  0  1  1  4  4 
 7  7  1  8  4  8  2  8  4  8  2  4 
 8  0  3  1  6  5  2  6  5  0  3  0 
 8  8  2  7  1  8  1  8  4  6  7  6 
 2  7  7  8  1  5  3  1  3  4  7  2 
 0  1  3  4  0  3  2  0  1  1  0  5 
 7  7  5  8  1  3  5  5  5  6  4  8 
 5  8  6  1  2  5  6  8  1  4  7  3 
 5  8  3  4  1  7  5  2  2  2  6  7 
 8  3  3  1  6  8  8  6  5  0  7  3 
Enter a digit to search for (or press q to quit): 5
Digit 5 occurrences:
1. In (0,7)
2. In (0,11)
3. In (1,10)
4. In (2,0)
5. In (2,4)
6. In (4,5)
7. In (4,8)
8. In (6,5)
9. In (7,11)
10. In (8,2)
11. In (8,6)
12. In (8,7)
13. In (8,8)
14. In (9,0)
15. In (9,5)
16. In (10,0)
17. In (10,6)
18. In (11,8)
Enter a digit to search for (or press q to quit): q
]0;maximilian.kaczmarek@csa3:~/assignment4maximilian.kaczmarek@csa3:~/assignment4$ ./assign4
Enter the size of the table:
2
 1  0 
 5  7 
Enter a digit to search for (or press q to quit): 0
Digit 0 occurrences:
1. In (0,1)
Enter a digit to search for (or press q to quit): q
]0;maximilian.kaczmarek@csa3:~/assignment4maximilian.kaczmarek@csa3:~/assignment4$ exit
exit

Script done on 2022-06-06 20:13:07-06:00
